server:
  port: 8102
  session-timeout: 60
  tomcat.uri-encoding: UTF-8
spring:
  data:
    mongodb:
#      host: 172.31.128.137
      host: 47.91.222.61
      port: 27017
      username: admin
      password: 3oRpuFHp
      database: bot
logging:
  level:
    org.apache.commons.httpclient: INFO